version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Entering install phase
      - mvn -q -DskipTests dependency:resolve

  pre_build:
    commands:
      - echo Entering pre_build phase
      - mvn -q validate

  build:
    commands:
      - echo Entering build phase
      - export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain ssk --domain-owner 563184259844 --region ap-south-1 --query authorizationToken --output text` && mvn deploy -DskipTests
      - cp -pvr settings.xml /root/.m2/settings.xml
      - ls -lrta /root/.m2/settings.xml
      - mvn deploy -DskipTests

  post_build:
    commands:
      - echo Build completed
      - ls -la target

artifacts:
  files:
    - target/*.jar
  discard-paths: yes

reports:
  junit:
    files:
      - target/surefire-reports/*.xml
    base-directory: target/surefire-reports
    discard-paths: yes
